platform :ios, "7.0"
source 'https://github.com/CocoaPods/Specs.git'

target "ProjectMonitor" do
  pod 'Parse'
  pod 'AFNetworking', '~> 2.0'
  pod 'Underscore.m'
  pod 'MBProgressHUD', '~> 0.8'
  pod 'MagicalRecord'
  pod 'BlocksKit'
  pod 'NewRelicAgent'
  pod 'CrashlyticsFramework'
  pod 'libPusher'
end

target "ProjectMonitorTests" do
  pod 'Kiwi'
  pod 'Parse'
  pod 'CrashlyticsFramework'
end
