platform :ios, "7.0"

target "ProjectMonitor" do
  pod 'Parse'
  pod 'AFNetworking', '~> 2.0'
  pod 'Underscore.m'
  pod 'MBProgressHUD', '~> 0.8'
  pod 'MagicalRecord'
  pod 'BlocksKit', :git => 'https://github.com/pandamonia/BlocksKit.git', :commit => '95833bd'
  pod 'NewRelicAgent'
  pod 'CrashlyticsFramework'

  target "ProjectMonitorTests", :exclusive => true do
    pod 'Kiwi/XCTest'
  end
end

