source 'https://rubygems.org'

ruby '2.1.1'

gem 'sidekiq'
#gem 'sidekiq-failures', git: 'git@github.com:mhfs/sidekiq-failures.git', branch: 'master'
gem 'httparty'
gem 'activesupport', require: 'active_support/all'
gem 'require_all'
gem 'settingslogic'
gem 'rufus-scheduler'
gem 'hashie'
gem 'rake'
gem 'redis-activesupport'
gem 'redis-semaphore'
gem 'pusher'
gem 'god'

group :development, :test do
  gem 'rack'
  gem 'rspec'
  gem 'rspec-its'
  gem 'fuubar'
  gem 'webmock', require: false
  gem 'sinatra'
  gem 'pry'
  gem 'timecop'
end
